"""
Classificação manual dos 276 códigos CBENEF de Goiás.

Estrutura por código:
  cat:           GENERICO | PRODUTO | CONTEXTO | IGNORE
  ncm_chapters:  lista de prefixos NCM (para PRODUTO).
  flags:         lista de flags que casam com perguntas do perfil da empresa.
                 Se a empresa responde NÃO a essa flag, o CBENEF é eliminado.
                 Vazia = não filtra por perfil (mantém sempre).
  nota:          descrição curta para a coluna OBSERVAÇÃO.
"""

# Perguntas do questionário (ordem de exibição)
PERFIL_PERGUNTAS = [
    # (flag, pergunta, default)
    ('exporta',            'A empresa exporta para o exterior?', 'n'),
    ('zfm',                'Vende para Zona Franca de Manaus ou outras áreas de livre comércio?', 'n'),
    ('doacao',             'Faz doações fiscais a entidades governamentais/assistenciais?', 'n'),
    ('orgao_publico',      'Vende para órgãos públicos (Sec. Educação, FNS, Min. Saúde, etc.)?', 'n'),
    ('drawback',           'Usa drawback ou outro regime aduaneiro especial?', 'n'),
    ('ativo_imobilizado',  'Tem operações frequentes com ativo imobilizado (compra/venda/transferência)?', 's'),
    ('mudanca_endereco',   'Realizou mudança de endereço de estabelecimento recentemente?', 'n'),
    ('sucessor_legal',     'Tem operação de sucessor legal (cisão, fusão sem saída física)?', 'n'),
    ('arrendamento',       'Faz arrendamento mercantil (leasing)?', 'n'),
    ('comodato',           'Envia mercadoria em comodato?', 'n'),
    ('demonstracao_mostr', 'Envia mercadoria para demonstração, feira ou mostruário?', 'n'),
    ('agropecuario',       'A empresa é produtor agropecuário ou trabalha com produto agropecuário?', 'n'),
    ('simples_nacional',   'É optante pelo Simples Nacional?', 'n'),
    ('ride',               'Opera na RIDE (Região Integrada de Desenvolvimento - Brasília/GO/DF)?', 'n'),
    # Setores específicos
    ('aeroespacial',       'É indústria aeroespacial ou fornecedor de empresa aeroespacial?', 'n'),
    ('sucroenergetico',    'Atua em setor sucroenergético (cana, etanol, biodiesel)?', 'n'),
    ('telecom',            'É operadora de telecomunicações?', 'n'),
    ('transporte_passag',  'Atua em transporte público de passageiros (ônibus, metrô, trem, táxi)?', 'n'),
    ('energia',            'É distribuidora de energia elétrica?', 'n'),
    ('farmaceutica',       'É indústria farmacêutica (medicamentos, vacinas)?', 'n'),
    ('reporto',            'É beneficiário do regime REPORTO (portuário)?', 'n'),
    ('befiex',             'É beneficiário do regime BEFIEX?', 'n'),
    ('fomentar_produzir',  'É beneficiário dos programas Fomentar ou Produzir (GO)?', 'n'),
    ('embarcacao_aeronave','Fabrica ou opera com embarcações/aeronaves?', 'n'),
    ('vestuario_cama_mesa','É fabricante de vestuário, roupas de cama, mesa ou banho?', 'n'),
    ('minerador',          'Atua em extração mineral (mineração)?', 'n'),
    ('reciclagem',         'É recicladora ou trabalha com resíduos/sucata?', 'n'),
    ('gas_combustivel',    'Revende gás (GLP) ou combustíveis (gasolina, diesel)?', 'n'),
    ('obra_arte',          'Comercializa obra de arte?', 'n'),
    ('concessionaria',     'É concessionária de serviço público (água, saneamento)?', 'n'),
    ('artesao',            'É artesão ou trabalhador manual?', 'n'),
]


CBENEF_GO_CLASSIFICACAO = {
    # ========== Não Incidência (GO800xxx) ==========
    'GO800001': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': ['exporta'],            'nota': 'Exportação'},
    'GO800002': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['gas_combustivel'],   'nota': 'Petróleo, combustível, energia elétrica'},
    'GO800003': {'cat': 'PRODUTO',   'ncm_chapters': ['71'], 'flags': [],                    'nota': 'Ouro como ativo financeiro'},
    'GO800004': {'cat': 'PRODUTO',   'ncm_chapters': ['48', '49'], 'flags': [],              'nota': 'Livro, jornal, periódico, papel'},
    'GO800005': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Mercadoria sujeita ao ISS'},
    'GO800006': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['sucessor_legal'],     'nota': 'Mercadoria a sucessor legal'},
    'GO800007': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Alienação fiduciária em garantia'},
    'GO800008': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['arrendamento'],       'nota': 'Arrendamento mercantil'},
    'GO800009': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Bem salvado de sinistro p/ seguradora'},
    'GO800010': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Remessa para depósito fechado do contribuinte'},
    'GO800011': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Remessa para armazém geral'},
    'GO800012': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['ativo_imobilizado'],  'nota': 'Saída de ativo imobilizado'},
    'GO800013': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['comodato'],           'nota': 'Saída em comodato'},
    'GO800014': {'cat': 'PRODUTO',   'ncm_chapters': ['97'], 'flags': ['obra_arte'],         'nota': 'Obra de arte'},
    'GO800015': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['mudanca_endereco'],   'nota': 'Mudança de endereço do estabelecimento'},
    'GO800016': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Saída interna p/ industrialização'},
    'GO800017': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Mera movimentação física (retorna)'},
    'GO800018': {'cat': 'PRODUTO',   'ncm_chapters': ['01','02','03','04','05','06','07','08','09','10','11','12','13','14'], 'flags': ['agropecuario'], 'nota': 'Produto agropecuário p/ beneficiamento'},
    'GO800019': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Campanha de assistência social'},
    'GO800020': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Saída entre estabelecimentos da mesma empresa'},
    'GO800021': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': ['demonstracao_mostr'], 'nota': 'Saída para demonstração'},
    'GO800022': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': ['demonstracao_mostr'], 'nota': 'Saída para mostruário ou treinamento'},
    'GO800023': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['exporta'],            'nota': 'Serviço de transporte (exportação)'},
    'GO800024': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['agropecuario'],       'nota': 'Serviço de transporte do produtor rural'},
    'GO800025': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['exporta','telecom'],  'nota': 'Serviço de comunicação ao exterior'},
    'GO809000': {'cat': 'IGNORE',    'ncm_chapters': None,  'flags': [],                     'nota': 'Reconhecida judicialmente'},

    # ========== Isenção (GO811xxx) ==========
    'GO811001': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['demonstracao_mostr'], 'nota': 'Mercadoria p/ exposição ou feira'},
    'GO811002': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico','concessionaria'], 'nota': 'Saída promovida por órgão público'},
    'GO811003': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Saída interestadual p/ conserto/reparo/industrialização'},
    'GO811004': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Refeição sem finalidade lucrativa'},
    'GO811005': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Venda à Itaipu Binacional'},
    'GO811006': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['embarcacao_aeronave'],'nota': 'Saída a embarcação/aeronave estrangeira'},
    'GO811007': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Doação a entidade governamental/assistencial'},
    'GO811008': {'cat': 'PRODUTO',   'ncm_chapters': ['97','42','44','46','58','62','63','69'], 'flags': ['artesao'], 'nota': 'Artesanato'},
    'GO811009': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica','orgao_publico'], 'nota': 'Produto farmacêutico entre órgãos públicos'},
    'GO811010': {'cat': 'PRODUTO',   'ncm_chapters': ['01','02','03','04','06','07','08'], 'flags': ['agropecuario'], 'nota': 'Hortifrutícola, pinto, ovo'},
    'GO811011': {'cat': 'PRODUTO',   'ncm_chapters': ['89'], 'flags': ['embarcacao_aeronave'], 'nota': 'Embarcação naval'},
    'GO811012': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Reprodutor/matriz animal'},
    'GO811013': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Reprodutor/matriz importado'},
    'GO811014': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Saída de instituição assistencial/educação'},
    'GO811015': {'cat': 'PRODUTO',   'ncm_chapters': ['04'], 'flags': [],                    'nota': 'Leite pasteurizado tipo especial'},
    'GO811016': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['zfm'],                'nota': 'Produto industrializado nacional p/ Zona Franca'},
    'GO811017': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Serviço de telecomunicação'},
    'GO811018': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Bem de operadora p/ instalação própria'},
    'GO811019': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Serviço de comunicação (publicidade)'},
    'GO811020': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['energia'],            'nota': 'Energia elétrica residencial'},
    'GO811021': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['transporte_passag'],  'nota': 'Transporte de passageiros urbano'},
    'GO811022': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Importação por org. internacional/estrangeira'},
    'GO811023': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['concessionaria'],     'nota': 'Água natural canalizada SANEAGO'},
    'GO811024': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['transporte_passag'],  'nota': 'Transporte rodoviário (táxi)'},
    'GO811025': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['drawback'],           'nota': 'Drawback (regime aduaneiro especial)'},
    'GO811026': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Saída de amostra grátis (qualquer produto)'},
    'GO811027': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['ativo_imobilizado'],  'nota': 'Ativo imobilizado entrado até 31/10/1996'},
    'GO811028': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['ativo_imobilizado'],  'nota': 'Ativo imobilizado p/ serviço fora'},
    'GO811029': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Retorno do art. 6º XXIX RCTE'},
    'GO811030': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['gas_combustivel','exporta'], 'nota': 'Combustível p/ embarcação/aeronave com destino exterior'},
    'GO811031': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['ativo_imobilizado'],  'nota': 'Ativo imobilizado interestadual p/ serviço fora'},
    'GO811032': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['energia','agropecuario'], 'nota': 'Energia elétrica produtor rural'},
    'GO811033': {'cat': 'PRODUTO',   'ncm_chapters': ['39','40','44','48','63','70','73','76'], 'flags': [], 'nota': 'Vasilhame, recipiente, embalagem retornável'},
    'GO811034': {'cat': 'PRODUTO',   'ncm_chapters': ['73','76'], 'flags': ['gas_combustivel'], 'nota': 'Botijão vazio de GLP'},
    'GO811035': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Loja franca em aeroporto'},
    'GO811036': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'P/ comercialização em loja franca'},
    'GO811037': {'cat': 'PRODUTO',   'ncm_chapters': ['84'], 'flags': ['agropecuario'],      'nota': 'Máquina para limpar fruta importada'},
    'GO811038': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Veículo adquirido por Sec. Segurança/Economia'},
    'GO811039': {'cat': 'PRODUTO',   'ncm_chapters': ['68','73'], 'flags': [],               'nota': 'Trava-bloco p/ casa popular'},
    'GO811040': {'cat': 'PRODUTO',   'ncm_chapters': ['05','01'], 'flags': ['agropecuario'], 'nota': 'Sêmen, embrião, oócito'},
    'GO811041': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Diferencial alíq. CIAC'},
    'GO811042': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Gado p/ criar/recriar/engorda'},
    'GO811043': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Produto de aula prática SENAC'},
    'GO811044': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Recebimento por órgão público (importação)'},
    'GO811045': {'cat': 'PRODUTO',   'ncm_chapters': ['05'], 'flags': ['agropecuario'],      'nota': 'Casulo do bicho-da-seda'},
    'GO811046': {'cat': 'PRODUTO',   'ncm_chapters': ['84','87'], 'flags': ['agropecuario'], 'nota': 'Trator agrícola/colheitadeira importados'},
    'GO811047': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Equino p/ cobertura/prova/treinamento'},
    'GO811048': {'cat': 'PRODUTO',   'ncm_chapters': ['06','07','08'], 'flags': ['agropecuario'], 'nota': 'Hortifrutícola p/ industrialização'},
    'GO811049': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Medicamentos AIDS'},
    'GO811050': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': ['befiex'],  'nota': 'Máquinas/equipamentos no Programa BEFIEX'},
    'GO811051': {'cat': 'PRODUTO',   'ncm_chapters': ['02','03','04','07','08','09','10','11','15','16','17','19','20','21','22'], 'flags': ['doacao'], 'nota': 'Produtos alimentícios p/ Banco de Alimentos'},
    'GO811052': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85'], 'flags': [],               'nota': 'Máquinas p/ Poliduto Replan-Brasília'},
    'GO811053': {'cat': 'PRODUTO',   'ncm_chapters': ['02','03','04','07','10','11','15','17','19'], 'flags': [], 'nota': 'Cesta básica'},
    'GO811054': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Convênio ICMS 18/95 (específico)'},
    'GO811055': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Amostra do exterior sem valor comercial'},
    'GO811056': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Bagagem de viajante'},
    'GO811057': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': [],          'nota': 'Máquinas EMBRAPA (pesquisa científica)'},
    'GO811058': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico','doacao'], 'nota': 'Doação importada para órgão público'},
    'GO811059': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': ['orgao_publico'], 'nota': 'Equipamento científico/informática órgão público'},
    'GO811060': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'EMBRATEL'},
    'GO811061': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['energia','telecom','orgao_publico'], 'nota': 'Energia elétrica/telecom p/ órgão público'},
    'GO811062': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Transporte ferroviário importação'},
    'GO811063': {'cat': 'PRODUTO',   'ncm_chapters': ['12'], 'flags': ['agropecuario'],      'nota': 'Mamona em baga'},
    'GO811064': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','87','90'], 'flags': [],     'nota': 'Equipamento p/ deficiente físico'},
    'GO811065': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Informática Sec. Economia GO'},
    'GO811066': {'cat': 'PRODUTO',   'ncm_chapters': ['39','40','41','44','47','48','50','51','52','53','54','55','63','70','72','73','74','75','76','78','79','80','81','83'], 'flags': ['reciclagem'], 'nota': 'Resíduo e sucata'},
    'GO811067': {'cat': 'PRODUTO',   'ncm_chapters': ['84'], 'flags': ['doacao'],            'nota': 'Microcomputador usado doado'},
    'GO811068': {'cat': 'PRODUTO',   'ncm_chapters': ['12'], 'flags': ['agropecuario'],      'nota': 'Caroço de algodão'},
    'GO811069': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['drawback'],           'nota': 'Admissão Temporária aduaneira'},
    'GO811070': {'cat': 'PRODUTO',   'ncm_chapters': ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15'], 'flags': ['agropecuario'], 'nota': 'Produção própria produtor agropecuário'},
    'GO811071': {'cat': 'PRODUTO',   'ncm_chapters': ['02','05','41','51'], 'flags': ['agropecuario'], 'nota': 'Produto não comestível de abate'},
    'GO811072': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Animal silvestre/exótico'},
    'GO811073': {'cat': 'PRODUTO',   'ncm_chapters': ['04'], 'flags': ['agropecuario'],      'nota': 'Leite em estado natural'},
    'GO811074': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Veículo Polícia Federal'},
    'GO811075': {'cat': 'PRODUTO',   'ncm_chapters': ['90'], 'flags': ['orgao_publico'],     'nota': 'Equipamento médico-hospitalar Min. Saúde'},
    'GO811076': {'cat': 'PRODUTO',   'ncm_chapters': ['39','73','76'], 'flags': ['agropecuario'], 'nota': 'Embalagem vazia de agrotóxico (devolução impositiva)'},
    'GO811077': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Veículo Polícia Rodoviária Federal'},
    'GO811078': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['agropecuario'],       'nota': 'Ativo fixo apicultor'},
    'GO811079': {'cat': 'PRODUTO',   'ncm_chapters': ['04'], 'flags': ['agropecuario'],      'nota': 'Produção própria apicultor'},
    'GO811080': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': [],          'nota': 'Aparelhos/máquinas/equipamentos importados'},
    'GO811081': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Furnas Centrais Elétricas - doação'},
    'GO811082': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Aquisição por órgão público estadual GO'},
    'GO811083': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['ativo_imobilizado'],  'nota': 'DIFAL ativo imobilizado industrial'},
    'GO811084': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['arrendamento'],       'nota': 'Venda do bem arrendado'},
    'GO811085': {'cat': 'PRODUTO',   'ncm_chapters': ['52'], 'flags': ['agropecuario'],      'nota': 'Algodão em retorno (descaroçamento)'},
    'GO811086': {'cat': 'PRODUTO',   'ncm_chapters': ['14'], 'flags': ['agropecuario'],      'nota': 'Bambu'},
    'GO811087': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['reciclagem'],         'nota': 'Produto reciclado p/ industrialização'},
    'GO811088': {'cat': 'PRODUTO',   'ncm_chapters': ['06'], 'flags': ['agropecuario'],      'nota': 'Muda de planta'},
    'GO811089': {'cat': 'PRODUTO',   'ncm_chapters': ['12','15','27'], 'flags': ['sucroenergetico'], 'nota': 'Vegetal p/ biodiesel/QAV alternativo'},
    'GO811090': {'cat': 'PRODUTO',   'ncm_chapters': ['85'], 'flags': ['reciclagem'],        'nota': 'Pilha e bateria usadas'},
    'GO811091': {'cat': 'PRODUTO',   'ncm_chapters': ['07','08','12','13'], 'flags': ['agropecuario'], 'nota': 'Produto típico cerrado p/ industrialização'},
    'GO811092': {'cat': 'PRODUTO',   'ncm_chapters': ['39','73','76'], 'flags': ['agropecuario'], 'nota': 'Embalagem de agrotóxico usada e lavada'},
    'GO811093': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['agropecuario'],       'nota': 'Granjas/aviários (projeto agroindustrial)'},
    'GO811094': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Produto farmacêutico/fralda FIOCRUZ'},
    'GO811095': {'cat': 'PRODUTO',   'ncm_chapters': ['12'], 'flags': ['agropecuario'],      'nota': 'Soja em retorno (industrialização)'},
    'GO811096': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85'], 'flags': [],               'nota': 'Máquinas industriais p/ indústria gráfica'},
    'GO811097': {'cat': 'PRODUTO',   'ncm_chapters': ['90'], 'flags': [],                    'nota': 'Medidor de vazão/condutivímetro p/ bebidas'},
    'GO811098': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Peça defeituosa em garantia'},
    'GO811099': {'cat': 'PRODUTO',   'ncm_chapters': ['26','74','75'], 'flags': ['minerador'], 'nota': 'Minério de níquel, cobre — DIFAL'},
    'GO811100': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Internet GESAC'},
    'GO811101': {'cat': 'PRODUTO',   'ncm_chapters': ['15'], 'flags': ['reciclagem'],        'nota': 'Óleo comestível usado'},
    'GO811102': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Animal vivo p/ abate'},
    'GO811103': {'cat': 'PRODUTO',   'ncm_chapters': ['03'], 'flags': ['agropecuario'],      'nota': 'Peixe produzido em GO'},
    'GO811104': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Internet escolas públicas'},
    'GO811105': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['embarcacao_aeronave'],'nota': 'Transporte aéreo - ativo imobilizado interestadual'},
    'GO811106': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Tratado Brasil-Ucrânia (Alcântara)'},
    'GO811107': {'cat': 'PRODUTO',   'ncm_chapters': ['61','62','63'], 'flags': ['vestuario_cama_mesa'], 'nota': 'Vestuário/cama/mesa/banho - transferência interna'},
    'GO811108': {'cat': 'PRODUTO',   'ncm_chapters': ['61','62','63'], 'flags': ['vestuario_cama_mesa','simples_nacional'], 'nota': 'Vestuário/cama/mesa/banho - Simples Nacional'},
    'GO811109': {'cat': 'PRODUTO',   'ncm_chapters': ['61','62','63'], 'flags': ['vestuario_cama_mesa'], 'nota': 'Vestuário/cama/mesa/banho - encomenda industrial'},
    'GO811110': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Aquisição interestadual de matéria-prima'},
    'GO811111': {'cat': 'PRODUTO',   'ncm_chapters': ['40'], 'flags': ['reciclagem'],        'nota': 'Pneu usado (reciclagem)'},
    'GO811112': {'cat': 'PRODUTO',   'ncm_chapters': ['85'], 'flags': ['orgao_publico'],     'nota': 'Equipamento de segurança eletrônica - Penitenciária'},
    'GO811113': {'cat': 'PRODUTO',   'ncm_chapters': ['25'], 'flags': ['minerador'],         'nota': 'Areia artificial p/ industrialização'},
    'GO811114': {'cat': 'PRODUTO',   'ncm_chapters': ['02','03','04','07','08','10','11','19','20'], 'flags': ['agropecuario'], 'nota': 'Gênero alimentício escolar (agricultor familiar)'},
    'GO811115': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Internet Popular'},
    'GO811116': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': ['agropecuario'], 'nota': 'Máquina ensaio têxtil (importação)'},
    'GO811117': {'cat': 'PRODUTO',   'ncm_chapters': ['87'], 'flags': [],                    'nota': 'Veículo automotor utilitário p/ feirante'},
    'GO811118': {'cat': 'PRODUTO',   'ncm_chapters': ['85'], 'flags': ['energia'],           'nota': 'Grupos geradores de energia elétrica'},
    'GO811119': {'cat': 'PRODUTO',   'ncm_chapters': ['87'], 'flags': ['orgao_publico'],     'nota': 'Veículo p/ Adm. Pública (industrial veículo)'},
    'GO811120': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Animal criado/engordado (projeto agroindustrial)'},
    'GO811121': {'cat': 'PRODUTO',   'ncm_chapters': ['09'], 'flags': ['agropecuario'],      'nota': 'Açafrão industrializado'},
    'GO811122': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Fármaco/medicamento Hemobrás'},
    'GO811123': {'cat': 'PRODUTO',   'ncm_chapters': ['39'], 'flags': ['fomentar_produzir'], 'nota': 'Extintores de incêndio descartáveis polímero'},
    'GO811124': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Telefonia fixa com franquia'},
    'GO811125': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['transporte_passag'],  'nota': 'Transporte público sobre trilhos'},
    'GO811126': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['artesao'],            'nota': 'Trabalhador Manual'},
    'GO811127': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['transporte_passag'], 'nota': 'Óleo diesel transporte coletivo'},
    'GO811128': {'cat': 'PRODUTO',   'ncm_chapters': ['22','27','29'], 'flags': ['sucroenergetico'], 'nota': 'Etanol anidro armazenagem dutoviária'},
    'GO811129': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['sucroenergetico','energia'], 'nota': 'Energia elétrica bagaço de cana'},
    'GO811130': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Gorjeta em alimentação'},
    'GO811131': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['energia'],            'nota': 'Energia elétrica compensação'},
    'GO811132': {'cat': 'PRODUTO',   'ncm_chapters': ['10'], 'flags': ['agropecuario'],      'nota': 'Trigo p/ industrialização'},
    'GO811133': {'cat': 'PRODUTO',   'ncm_chapters': ['85'], 'flags': ['energia'],           'nota': 'Geração de energia solar'},
    'GO811134': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['energia'],            'nota': 'Energia elétrica PJ sem fins lucrativos'},
    'GO811135': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Bens e mercadorias digitais'},
    'GO811136': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Remessa internacional devolvida courier'},
    'GO811137': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Bazar entidade espírita OSCEIA'},
    'GO811138': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Medicamento Spinraza (AME)'},
    'GO811139': {'cat': 'PRODUTO',   'ncm_chapters': ['90'], 'flags': ['farmaceutica'],      'nota': 'Aceleradores lineares NCM 9022.21.90'},
    'GO811140': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['reciclagem'],        'nota': 'Óleo lubrificante usado/contaminado'},
    'GO811141': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Vacinas Coronavírus'},
    'GO811900': {'cat': 'IGNORE',    'ncm_chapters': None,  'flags': [],                     'nota': 'Reconhecida judicialmente'},

    # ========== Isenção Convênio (GO812xxx) ==========
    'GO812001': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Importação p/ fracionamento de sangue'},
    'GO812002': {'cat': 'PRODUTO',   'ncm_chapters': ['90','84','85'], 'flags': ['orgao_publico'], 'nota': 'Bens importados p/ ensino/pesquisa/saúde'},
    'GO812003': {'cat': 'PRODUTO',   'ncm_chapters': ['87','90'], 'flags': [],               'nota': 'Apêndice III - mercadoria p/ deficiente'},
    'GO812004': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica','doacao'], 'nota': 'Medicamentos importados APAE'},
    'GO812005': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario'],      'nota': 'Reprodutor/matriz caprino importado'},
    'GO812006': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Doação à Sec. Educação'},
    'GO812007': {'cat': 'PRODUTO',   'ncm_chapters': ['03'], 'flags': ['agropecuario'],      'nota': 'Pós-larva de camarão'},
    'GO812008': {'cat': 'PRODUTO',   'ncm_chapters': ['25'], 'flags': ['minerador'],         'nota': 'Transporte de calcário (programa ambiental)'},
    'GO812009': {'cat': 'PRODUTO',   'ncm_chapters': ['87'], 'flags': [],                    'nota': 'Veículo p/ deficiente físico/visual/mental/autista'},
    'GO812010': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['concessionaria'],     'nota': 'Saneamento básico - importação'},
    'GO812011': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Doação ao Governo - distribuição gratuita'},
    'GO812012': {'cat': 'PRODUTO',   'ncm_chapters': ['87'], 'flags': ['transporte_passag'], 'nota': 'Veículo automotor p/ táxi'},
    'GO812013': {'cat': 'PRODUTO',   'ncm_chapters': ['30','38'], 'flags': ['farmaceutica'], 'nota': 'Diagnóstico imunohematologia/sorologia'},
    'GO812014': {'cat': 'PRODUTO',   'ncm_chapters': ['40'], 'flags': ['farmaceutica'],      'nota': 'Preservativo NCM 4014.10'},
    'GO812015': {'cat': 'PRODUTO',   'ncm_chapters': ['12','23','29','30','31','38'], 'flags': ['agropecuario'], 'nota': 'Insumos agropecuários'},
    'GO812016': {'cat': 'PRODUTO',   'ncm_chapters': ['85'], 'flags': ['energia'],           'nota': 'Sistemas geração energia solar/eólica'},
    'GO812017': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': ['orgao_publico'], 'nota': 'Equipamento didático/científico/médico MEC'},
    'GO812018': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['agropecuario'],       'nota': 'Ativo imobilizado EMBRAPA'},
    'GO812019': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Doação p/ vítima de seca'},
    'GO812020': {'cat': 'PRODUTO',   'ncm_chapters': ['28','29','30','38','90'], 'flags': ['farmaceutica'], 'nota': 'Equipamentos/insumos serviços saúde'},
    'GO812021': {'cat': 'PRODUTO',   'ncm_chapters': ['30','38'], 'flags': ['farmaceutica','orgao_publico'], 'nota': 'Campanhas vacinação (dengue, malária)'},
    'GO812022': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Medicamentos Conv. ICMS 140/01'},
    'GO812023': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica','orgao_publico'], 'nota': 'Fármaco/medicamento p/ Adm. Pública'},
    'GO812024': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Soro conservante de córnea'},
    'GO812025': {'cat': 'PRODUTO',   'ncm_chapters': ['28','29','30'], 'flags': ['farmaceutica'], 'nota': 'Matéria-prima p/ fármaco importado'},
    'GO812026': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Doação Programa Fome Zero'},
    'GO812027': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Transporte de cargas interno'},
    'GO812028': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Doação à OVG'},
    'GO812029': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Projeto Roraima'},
    'GO812030': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['doacao'],             'nota': 'Doação Vila São Bento Cotollengo'},
    'GO812031': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Modernização áreas fiscal'},
    'GO812032': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['reporto'],            'nota': 'Ativo imobilizado REPORTO'},
    'GO812033': {'cat': 'PRODUTO',   'ncm_chapters': ['85'], 'flags': ['energia'],           'nota': 'Acumuladores elétricos FURNAS'},
    'GO812034': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['agropecuario'],       'nota': 'CDA/WA (depósito agropecuário)'},
    'GO812035': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': [],          'nota': 'Máquinas importadas SENAI/SENAC/SENAR'},
    'GO812036': {'cat': 'PRODUTO',   'ncm_chapters': ['28','29','30','38'], 'flags': ['farmaceutica'], 'nota': 'Medicamento e reagente químico Apêndice XXX'},
    'GO812037': {'cat': 'PRODUTO',   'ncm_chapters': ['85'], 'flags': ['telecom'],           'nota': 'Importação radiodifusão'},
    'GO812038': {'cat': 'PRODUTO',   'ncm_chapters': ['30','38'], 'flags': ['farmaceutica','orgao_publico'], 'nota': 'Reagente Doença de Chagas'},
    'GO812039': {'cat': 'PRODUTO',   'ncm_chapters': ['87','89'], 'flags': ['orgao_publico'],'nota': 'Transporte escolar FNDE'},
    'GO812040': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['embarcacao_aeronave'],'nota': 'Peça defeituosa - aeronave'},
    'GO812041': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Fosfato de oseltamivir (H1N1)'},
    'GO812042': {'cat': 'PRODUTO',   'ncm_chapters': ['03'], 'flags': ['agropecuario'],      'nota': 'Pós-larva de camarão e reprodutores SPF importados'},
    'GO812043': {'cat': 'PRODUTO',   'ncm_chapters': ['03'], 'flags': ['agropecuario'],      'nota': 'Reprodutor camarão marinho'},
    'GO812044': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Sanduíche BIG MAC McDia Feliz'},
    'GO812045': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': ['doacao'],  'nota': 'Equipamentos ACCEG/Hospital de Câncer'},
    'GO812046': {'cat': 'PRODUTO',   'ncm_chapters': ['90'], 'flags': ['farmaceutica'],      'nota': 'Equipamento respiratório Elmo (Coronavírus)'},
    'GO812047': {'cat': 'PRODUTO',   'ncm_chapters': ['28'], 'flags': ['farmaceutica'],      'nota': 'Oxigênio medicinal NCM 2804.40.00'},
    'GO812048': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica'],      'nota': 'Medicamentos Apêndice XLVIII'},
    'GO812900': {'cat': 'IGNORE',    'ncm_chapters': None,  'flags': [],                     'nota': 'Reconhecida judicialmente'},

    # ========== Redução BC (GO821xxx) ==========
    'GO821001': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Mercadoria usada (saída não onerada na entrada)'},
    'GO821002': {'cat': 'PRODUTO',   'ncm_chapters': ['04'], 'flags': [],                    'nota': 'Leite pasteurizado tipo especial'},
    'GO821003': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['gas_combustivel'],   'nota': 'GLP'},
    'GO821004': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': ['befiex'],  'nota': 'Máquina importada BIFIEX'},
    'GO821005': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Saída interna p/ comercialização/produção/industrialização'},
    'GO821006': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'TV por assinatura'},
    'GO821007': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Refeições em bares/restaurantes'},
    'GO821008': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85'], 'flags': [],               'nota': 'Informática/telecom/automação Apêndice IV'},
    'GO821009': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Radiochamada'},
    'GO821010': {'cat': 'PRODUTO',   'ncm_chapters': ['10','07'], 'flags': ['agropecuario'], 'nota': 'Arroz e feijão industrializados'},
    'GO821011': {'cat': 'PRODUTO',   'ncm_chapters': ['25','68'], 'flags': ['minerador'],    'nota': 'Areia natural/artificial, saibro, britado'},
    'GO821012': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Anexo I do RCTE (lista específica)'},
    'GO821013': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Conv. ICMS 34/06 (lista específica)'},
    'GO821014': {'cat': 'PRODUTO',   'ncm_chapters': ['84','87'], 'flags': [],               'nota': 'Máquinas e equipamentos rodoviários'},
    'GO821015': {'cat': 'PRODUTO',   'ncm_chapters': ['69'], 'flags': [],                    'nota': 'Telha, tijolo, tijoleira cerâmicos'},
    'GO821016': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['gas_combustivel'],   'nota': 'Gasolina de aviação'},
    'GO821017': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['ativo_imobilizado'],  'nota': 'Ativo imobilizado industrial/agropecuário'},
    'GO821018': {'cat': 'PRODUTO',   'ncm_chapters': ['52'], 'flags': ['agropecuario'],      'nota': 'Algodão em pluma'},
    'GO821019': {'cat': 'PRODUTO',   'ncm_chapters': ['02','03','04','07','10','11','15','17','19'], 'flags': [], 'nota': 'Cesta básica'},
    'GO821020': {'cat': 'PRODUTO',   'ncm_chapters': ['96','48','39'], 'flags': [],          'nota': 'Fralda descartável'},
    'GO821021': {'cat': 'PRODUTO',   'ncm_chapters': ['87'], 'flags': [],                    'nota': 'Caminhão > 5 toneladas / caminhão-trator'},
    'GO821022': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Lei 13.453/99 (lista específica)'},
    'GO821023': {'cat': 'PRODUTO',   'ncm_chapters': ['25','68'], 'flags': ['minerador'],    'nota': 'Mármore e granito de GO'},
    'GO821024': {'cat': 'PRODUTO',   'ncm_chapters': ['07','08','09','12','13','20','21'], 'flags': ['agropecuario'], 'nota': 'Produto típico cerrado industrializado (exc. álcool)'},
    'GO821025': {'cat': 'PRODUTO',   'ncm_chapters': ['02'], 'flags': ['agropecuario'],      'nota': 'Carne e produtos comestíveis de gado'},
    'GO821026': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': [],                    'nota': 'Massa asfáltica'},
    'GO821027': {'cat': 'PRODUTO',   'ncm_chapters': ['25','68'], 'flags': ['minerador'],    'nota': 'Pedra-de-pirenópolis'},
    'GO821028': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Monitoramento/rastreamento veículo/carga'},
    'GO821029': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['telecom'],            'nota': 'Publicidade em TV por assinatura'},
    'GO821030': {'cat': 'PRODUTO',   'ncm_chapters': ['87'], 'flags': ['transporte_passag'], 'nota': 'Ônibus / chassi com motor'},
    'GO821031': {'cat': 'PRODUTO',   'ncm_chapters': ['40'], 'flags': [],                    'nota': 'Pneumático novo / câmara-de-ar'},
    'GO821032': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['orgao_publico'],      'nota': 'Adm. Pública - UMS'},
    'GO821033': {'cat': 'PRODUTO',   'ncm_chapters': ['72','73','76','85'], 'flags': ['sucroenergetico'], 'nota': 'LT e subestação EE bagaço de cana'},
    'GO821034': {'cat': 'PRODUTO',   'ncm_chapters': ['39','48','73','76','40','63'], 'flags': [], 'nota': 'Embalagem p/ industrial de adubo/fertilizante'},
    'GO821035': {'cat': 'PRODUTO',   'ncm_chapters': ['28','29','38','39','84','85','90'], 'flags': [], 'nota': 'Tratamento de efluentes industriais/domésticos'},
    'GO821036': {'cat': 'GENERICO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Integrante de grupo econômico - p/ comercialização/produção/industrialização'},
    'GO821037': {'cat': 'PRODUTO',   'ncm_chapters': ['30'], 'flags': ['farmaceutica','orgao_publico'], 'nota': 'Medicamento humano p/ Adm. Pública/hospital'},
    'GO821038': {'cat': 'PRODUTO',   'ncm_chapters': ['87'], 'flags': [],                    'nota': 'Veículo automotor'},
    'GO821039': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Bem/material/peça defeituoso em assistência técnica'},
    'GO821900': {'cat': 'IGNORE',    'ncm_chapters': None,  'flags': [],                     'nota': 'Reconhecida judicialmente'},

    # ========== Redução BC Convênio (GO822xxx) ==========
    'GO822001': {'cat': 'PRODUTO',   'ncm_chapters': ['84','85','90'], 'flags': [],          'nota': 'Máquina e equipamento Apêndices V e VI'},
    'GO822002': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['aeroespacial'],       'nota': 'Conv. ICMS 75/91 (lista específica - aeroespacial)'},
    'GO822003': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Conv. ICMS 50/93 (lista específica)'},
    'GO822004': {'cat': 'PRODUTO',   'ncm_chapters': ['12','23','29','30','31','38'], 'flags': ['agropecuario'], 'nota': 'Insumos agropecuários Conv. 100/97 cl.1'},
    'GO822005': {'cat': 'PRODUTO',   'ncm_chapters': ['12','23','29','30','31','38'], 'flags': ['agropecuario'], 'nota': 'Insumos agropecuários Conv. 100/97 cl.2'},
    'GO822006': {'cat': 'PRODUTO',   'ncm_chapters': ['23'], 'flags': ['agropecuario'],      'nota': 'Farelo gordo de arroz - ração animal'},
    'GO822007': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Apêndices XVIII-XX (lista específica)'},
    'GO822008': {'cat': 'PRODUTO',   'ncm_chapters': ['07','11','19','20'], 'flags': ['agropecuario'], 'nota': 'Industrialização de mandioca'},
    'GO822009': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['gas_combustivel','embarcacao_aeronave'], 'nota': 'Querosene de aviação'},
    'GO822010': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['gas_combustivel'],   'nota': 'Gás natural de GNL'},
    'GO822011': {'cat': 'PRODUTO',   'ncm_chapters': ['38'], 'flags': ['sucroenergetico'],   'nota': 'Biodiesel B-100'},
    'GO822012': {'cat': 'PRODUTO',   'ncm_chapters': ['01'], 'flags': ['agropecuario','ride'], 'nota': 'Bovino RIDE p/ abate DF'},
    'GO822013': {'cat': 'PRODUTO',   'ncm_chapters': ['44'], 'flags': ['agropecuario'],      'nota': 'Madeira p/ industrialização'},
    'GO822014': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['simples_nacional'],   'nota': 'Importação Paraguai - Simples Nacional'},
    'GO822015': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': [],                     'nota': 'Min. Defesa - industrial fabricante'},
    'GO822016': {'cat': 'CONTEXTO',  'ncm_chapters': None,  'flags': ['transporte_passag'],  'nota': 'Transporte intermunicipal passageiros'},
    'GO822017': {'cat': 'PRODUTO',   'ncm_chapters': ['27'], 'flags': ['gas_combustivel','embarcacao_aeronave'], 'nota': 'QAV p/ transporte aéreo'},
    'GO822018': {'cat': 'PRODUTO',   'ncm_chapters': ['12','23','29','30','31','38'], 'flags': ['agropecuario'], 'nota': 'Conv. ICMS 100/97 (importação, internas, interestaduais)'},
    'GO822900': {'cat': 'IGNORE',    'ncm_chapters': None,  'flags': [],                     'nota': 'Reconhecida judicialmente'},
}
